package com.jiyun.lenovo.app;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.myteam.Bean.PeopleBean;

import com.jiyun.lenovo.app.PeopleBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig peopleBeanDaoConfig;

    private final PeopleBeanDao peopleBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        peopleBeanDaoConfig = daoConfigMap.get(PeopleBeanDao.class).clone();
        peopleBeanDaoConfig.initIdentityScope(type);

        peopleBeanDao = new PeopleBeanDao(peopleBeanDaoConfig, this);

        registerDao(PeopleBean.class, peopleBeanDao);
    }
    
    public void clear() {
        peopleBeanDaoConfig.clearIdentityScope();
    }

    public PeopleBeanDao getPeopleBeanDao() {
        return peopleBeanDao;
    }

}
